language: php
php:
  - 7.1
sudo: required
install:
  - composer install --optimize-autoloader
script: ${TRAVIS_BUILD_DIR}/vendor/bin/phpunit
after_success:
  - sudo chmod 777 -R ${TRAVIS_BUILD_DIR}/build
  - travis_retry php vendor/bin/php-coveralls -v -r ${TRAVIS_BUILD_DIR}