language: php
php:
  - 7.1
sudo: required
services:
  - docker
install:
  - composer install --optimize-autoloader
  - docker-compose build unittest
script: sh ./bin/go-test.sh
after_success:
  - docker-compose down
  - sudo chmod 777 -R ${TRAVIS_BUILD_DIR}/build
  - travis_retry php vendor/bin/php-coveralls -v -r ${TRAVIS_BUILD_DIR}